export enum SystemParameterName {
	TimerDurationInS = 'TimerDurationInS',
	ShouldLimitFreePoints = 'ShouldLimitFreePoints',
	FreePointsMinimum = 'FreePointsMinimum',
	MinimumNumberOfWishlistGames = 'MinimumNumberOfWishlistGames',
	AvailableRollChangeByRoll = 'AvailableRollChangeByRoll',
	MaximumAvailableRollCountForTimer = 'MaximumAvailableRollCountForTimer',
	MinimumAvailableRollCountForRoll = 'MinimumAvailableRollCountForRoll',
	SeizePenaltyPoints = 'SeizePenaltyPoints',
	AvailableRollChangeByTimer = 'AvailableRollChangeByTimer',
	TerritoryHourChangeByTimer = 'TerritoryHourChangeByTimer',
	ExperiencePointChangeByTimer = 'ExperiencePointChangeByTimer',
	ExperiencePointChangeByLevelUp = 'ExperiencePointChangeByLevelUp',
	TerritoryHourChangeBySeizeSlice = 'TerritoryHourChangeBySeizeSlice',
}
